### ISSUE TITLE
[BUG] Add package without variables

### ISSUE THREAD

**Issue by andrey-canon** [eduNEXT/tutor-contrib-edunext-distro#28]
**Describe the bug**
If a package is added without variables this  will raise the following error
![image](https://user-images.githubusercontent.com/36200299/190263652-8c1c3d90-b952-4e7d-80ea-8a96d631264d.png)

**To Reproduce**
1. Add a package like this 
```
DISTRO_DJANGO_PASSWORD_VALIDATORS_DPKG:
  index: pip
  name: django-password-validators
  private: false
  version: 1.7.0
  private: true
```
2. with stack builder runs `stack strain dev configure -c`

**Desired  behavior**
if the attribute variables is not set, apply empty default values
