### ISSUE TITLE
[BUG] Bargi theme repository for quince not found 

### ISSUE THREAD

**Issue by alexshikov** [eduNEXT/tutor-contrib-edunext-distro#65]
**Describe the bug**
Running `tutor distro enable-themes` after updating the `config.yml` as per Readme, fails with error `Repository not found. Could not read from remote repository`.

tutor version: 17.0.4

**To Reproduce**
1. Update `config.yml` file with settings as per Readme:
```yml
DISTRO_THEMES:
- domain: github.com
  name: ednx-saas-themes
  path: eduNEXT
  protocol: ssh
  repo: ednx-saas-themes
  version: edunext/quince.master
DISTRO_THEMES_NAME:
- bragi
DISTRO_THEMES_ROOT: /openedx/themes
DISTRO_THEME_DIRS:
- /openedx/themes/ednx-saas-themes/edx-platform
- /openedx/themes/ednx-saas-themes/edx-platform/bragi-generator
- /openedx/themes/ednx-saas-themes/edx-platform/bragi-children
OPENEDX_EXTRA_PIP_REQUIREMENTS:
- eox-tenant==v11.2.0
- eox-theming==v7.0.0
```
2. `tutor config save`
3. `tutor distro enable-themes`
5. See error
```sh
> tutor distro enable-themes
Cloning into '/Users/admin/Library/Application Support/tutor/env/build/openedx/themes/ednx-saas-themes'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Expected behavior**
Should the bargi theme for quince be accessible and `tutor distro enable-themes` run successfully?

**Additional context**
We've tried to use publicly available `palm` version from this repo https://github.com/eduNEXT/ednx-saas-themes-nelp/tree/ednx-release/palm.nelp, even though it installed, built and launched successfully, opening `lacolhost.com` shows blank page, which looks expected due to incompatibility of theme and the platform versions.
